project_name: lelan-release
run_name: lelan

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 256
eval_batch_size: 400
epochs: 100
gpu_ids: [0]
num_workers: 1 #12
lr: 1e-4
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 4
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

# model params
model_type: lelan #lnp_freeze_clip
vision_encoder: lelan_clip_film
encoding_size: 256
obs_encoder: efficientnet-b0
clip_type: "ViT-B/32"
cond_predict_scale: False
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
down_dims: [64, 128, 256]

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 0 # 1
alpha: 1e-4

# action output params
len_traj_pred: 24
learn_angle: False

# dataset specific parameters
image_size: [224, 224] # width, height
feature_size: 4096

datasets:  
  go_stanford4:
    train: ../dataset/lelan_gs4/train/
    test: ../dataset/lelan_gs4/test/
    image: ../dataset/dataset_LeLaN_gs4/image/
    pickle: ../dataset/dataset_LeLaN_gs4/pickle/
    backside: False
    aug_seq: False
    only_front: False
            
  sacson:
    train: ../dataset/lelan_sacson/train/
    test: ../dataset/lelan_sacson/test/
    image: ../dataset/dataset_LeLaN_sacson/
    pickle: ../dataset/dataset_LeLaN_sacson/
    backside: False
    aug_seq: False
    only_front: False
            
  go_stanford2:
    train: ../dataset/lelan_gs2/train/
    test: ../dataset/lelan_gs2/test/
    image: ../dataset/dataset_LeLaN_gs2/
    pickle: ../dataset/dataset_LeLaN_gs2/
    backside: False
    aug_seq: False
    only_front: False

  humanw:
    train: ../dataset/lelan_humanw/train/
    test: ../dataset/lelan_humanw/test/
    image: ../dataset/dataset_LeLaN_humanwalk/
    pickle: ../dataset/dataset_LeLaN_humanwalk/    
    backside: False
    aug_seq: False 
    only_front: True   

  youtube:
    train: ../dataset/lelan_youtube/train/
    test: ../dataset/lelan_youtube/test/
    image: ../dataset/dataset_LeLaN_youtube/
    pickle: ../dataset/dataset_LeLaN_youtube/        
    backside: False
    aug_seq: False 
    only_front: True  
        
# logging stuff
print_log_freq: 1000 # in iterations
image_log_freq: 40 #0 # in iterations 1000 40
num_images_log: 8 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 1. # 0.25
wandb_log_freq: 10 # in iterations
eval_freq: 1 # in epochs 20
save_freq: 1 # in epochs

load_run: lelan-release/lelan_2024_09_16_18_12_27 #xxxxxxxx is the folder of the pretrained checkpoint
